"""Phase 4.6: generate results_v3/CHANGELOG.md — every number that changed
versus the old report (results/IAMA_Net_Academic_Research_Report.md), with
the reason and the CSV source. Values are read from the audit/eval CSVs;
claim texts are quoted from the old report (file + section).
"""

import csv
import json
from pathlib import Path

from iama_env import AUDIT_DIR, PROJECT_ROOT

RV3 = PROJECT_ROOT / "results_v3"


def read_csv(path):
    if not Path(path).exists():
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def get(rows, **kw):
    for r in rows:
        if all(str(r.get(k, "")) == str(v) for k, v in kw.items()):
            return r
    return {}


def main():
    recon = read_csv(AUDIT_DIR / "reconciliation_neu.csv")
    recon_gc = read_csv(AUDIT_DIR / "reconciliation_gc10.csv")
    cw = read_csv(AUDIT_DIR / "reconciliation_classwise.csv")
    params = {r["model"]: r for r in read_csv(AUDIT_DIR / "param_counts.csv")}
    abl = read_csv(RV3 / "ablation_matched.csv")
    cross = read_csv(RV3 / "cross_dataset_matched.csv")
    paired_old = read_csv(AUDIT_DIR / "paired_bootstrap_m4_vs_m1.csv")
    fps_old = read_csv(AUDIT_DIR / "fps_benchmark_summary.csv")
    fps_new = read_csv(AUDIT_DIR / "matched_fps_benchmark_summary.csv")
    attn = read_csv(RV3 / "attention_alternatives.csv")
    restr = read_csv(AUDIT_DIR / "gc10_restricted_overlap.csv")
    da = json.loads((AUDIT_DIR / "data_audit_summary.json").read_text())

    L = []
    A = L.append
    A("# CHANGELOG — old report → v3 (audit + matched re-run)")
    A("")
    A("Generated by `scripts_v3/make_changelog.py` from the CSVs listed per entry.")
    A("Old report: `results/IAMA_Net_Academic_Research_Report.md` (frozen, read-only).")
    A("New report: `results_v3/IAMA_Net_report_v3.md`. Full audit: `results_v3/audit/audit_report.md`.")
    A("")
    A("## A. Numbers that were REAL and reproduced exactly")
    A("")
    A("Old master-table mAP@0.5 values all reproduce from the original checkpoints (±0.0002,")
    A("`results_v3/audit/reconciliation_neu.csv`): M1 0.7527, M2 0.7444, M3 0.7484, M4 0.7333,")
    A("anchor 0.7608. Old GC10 test-split values also reproduce (M1 0.0311→0.0312, M4 0.0466,")
    A("P/R within 0.002; `reconciliation_gc10.csv`). The old numbers were computed honestly —")
    A("the PROTOCOL was the problem (see C).")
    A("")
    A("## B. Numbers that were WRONG or unsourced in the old report")
    A("")
    A("| # | old claim | old value | corrected value | reason | source |")
    A("|---|---|---|---|---|---|")
    m2_95 = get(recon, model="M2", metric="mAP@0.5:0.95")
    A(f"| 1 | §4.1 mAP@0.5:0.95 column | 0.4204/0.4240/0.4070/0.4170/0.4060 | M1 {get(recon, model='M1', metric='mAP@0.5:0.95')['new_ultralytics_val']}, "
      f"M2 {m2_95['new_ultralytics_val']}, M3 {get(recon, model='M3', metric='mAP@0.5:0.95')['new_ultralytics_val']}, "
      f"M4 {get(recon, model='M4', metric='mAP@0.5:0.95')['new_ultralytics_val']}, anchor {get(recon, model='ANCHOR', metric='mAP@0.5:0.95')['new_ultralytics_val']} | "
      "column had no CSV provenance in repo; recomputed from checkpoints | reconciliation_neu.csv |")
    A("| 2 | §4.2 class-wise table 'M1' column | crazing 0.490, mean 0.7608 | M1 real: crazing 0.449, mean 0.7527 | "
      "table was generated from the identity-mapped ANCHOR checkpoint (total dev 0.0019 vs 0.0646) | reconciliation_classwise.csv |")
    A("| 3 | §4.2 class-wise M2/M3/M4 columns | e.g. inclusion 0.866/0.878/0.865 | inclusion spans 0.782–0.788 across ALL five checkpoints | "
      "columns match no checkpoint in the repo (max per-class dev 0.10–0.14) | reconciliation_classwise.csv |")
    A("| 4 | Abstract 'inclusion 78.1% → 87.8% (+9.7 pp)' | +9.7 pp | not reproducible; matched-protocol M1→M4 inclusion: "
      f"{get(abl, variant='M1').get('AP50_inclusion','')} → {get(abl, variant='M4').get('AP50_inclusion','')} (+{(float(get(abl, variant='M4').get('AP50_inclusion', 0))-float(get(abl, variant='M1').get('AP50_inclusion', 0)))*100:.1f} pp) | "
      "old value exists in no artifact; matched re-run gives +1.2 pp | ablation_matched.csv |")
    A(f"| 5 | Abstract param overhead | 309 | **315** (3×105; ECA k=5) | 309 assumes k=3; recount from checkpoints | param_counts.csv |")
    A(f"| 6 | §2.2 baseline params | 9,415,122 | 9,415,122 fused / {params.get('ckpt_M1', {}).get('total_params', '?')} unfused | report quoted fused count without saying so | param_counts.csv |")
    A("| 7 | §2.2 feature-map channels P3/P4/P5 | 128/256/512 | 256/256/512 | forward probe on actual model | audit_report.md §4 |")
    gc_boxes = da["gc10_metadata_jsonl"]["total_boxes"]
    A(f"| 8 | §3.2 GC10 facts | '2,303 images', 10th class 'rolled-in scale' | 2,300 images, {gc_boxes} boxes, 10th class rolled_pit | 2,303 counted 3 metadata.jsonl files | data_audit_summary.json |")
    A("| 9 | §1/§3 'high-resolution' NEU-DET | — | 200×200 grayscale | data audit | data_audit_summary.json |")
    A("| 10 | Abstract '+49.8% relative GC10 gain' | 0.0311→0.0466 (+49.8% rel) | matched protocol, all 2,300 images: M4 **−1.03 pp vs baseline (p<0.001, WORSE)**; "
      "original checkpoints on all images: +0.32 pp (p=0.17, ns) | old value = 230-image subset of a confounded protocol | cross_dataset_matched.csv, paired_bootstrap_m4_vs_m1.csv |")
    A("| 11 | §4.1 'precision gain halves false alarms' | 8.6%→16.6% precision | false detections 91%→83% of detections (original ckpts); matched models: no transfer gain | mischaracterisation | audit_report.md §6 |")
    fpso = {r["model"]: r for r in fps_old if r["precision"] == "fp32" and r["source"] == "real_neu_test_image"}
    fpsn = {r["model"]: r for r in fps_new if r["precision"] == "fp32" and r["source"] == "real_neu_test_image"}
    A(f"| 12 | §5.3 FPS table | M1 59.5 / M2 51.6 / M3 44.4 / M4 43.5 (and 67.7/57.2 elsewhere) | "
      f"controlled: M1m {fpsn.get('M1m', {}).get('fps_mean', '?')}, M2m {fpsn.get('M2m', {}).get('fps_mean', '?')}, "
      f"M3m {fpsn.get('M3m', {}).get('fps_mean', '?')}, M4m {fpsn.get('M4m', {}).get('fps_mean', '?')} FPS fp32 | "
      "old protocol (10 warmup/50 timed, no repeats, noise input) not reproducible; same-arch spread was up to 25% | matched_fps_benchmark_summary.csv |")
    A("| 13 | §2.2 CLAHE clip-limit formula | 'ray-traced contrast limit' formula | OpenCV semantics: clipLimit multiplies mean bin height | not a CLAHE concept; formula wrong | audit_report.md §10 |")
    A("| 14 | §3.3 'identical hyperparameters' | claimed | false: M2–M4 = 25/25/30-epoch fine-tunes of converged M1, M3/M4 with 10 frozen layers, different LR schedule | args.yaml evidence | audit_report.md §9 |")
    A("")
    A("## C. Headline results that CHANGED SIGN under the matched protocol")
    A("")
    A("Old (confounded): M4 was the WORST model in-domain — mAP@0.5 0.7333 vs baseline 0.7527")
    A("(−1.94 pp; paired p=0.072; mAP@0.5:0.95 −1.44 pp, p=0.028 significantly worse), with")
    A("per-class collapses (crazing −10.4 pp, patches −13.2 pp, rolled-in scale −8.9 pp vs old M1 column).")
    A("")
    m4 = get(abl, variant="M4")
    m1 = get(abl, variant="M1")
    A(f"New (matched, 100 epochs, seed 0, COCO init, no freezing): M4 is the BEST model —")
    A(f"mAP@0.5 {m1['mAP50_val']} → {m4['mAP50_val']} (**+{m4.get('delta_mAP50_vs_M1_pp','?')} pp, p={m4.get('delta_mAP50_p','?')}**),")
    A(f"mAP@0.5:0.95 {m1['mAP5095_val']} → {m4['mAP5095_val']} (+{m4.get('delta_mAP5095_vs_M1_pp','?')} pp, p={m4.get('delta_mAP5095_p','?')} — inconclusive).")
    A(f"Per-class: crazing {m1.get('AP50_crazing','')} → {m4.get('AP50_crazing','')} (+{(float(m4.get('AP50_crazing',0))-float(m1.get('AP50_crazing',0)))*100:.1f} pp), "
      f"patches {m1.get('AP50_patches','')} → {m4.get('AP50_patches','')}, rolled-in scale {m1.get('AP50_rolled-in_scale','')} → {m4.get('AP50_rolled-in_scale','')}.")
    A("")
    A("Reason: the old ablation fine-tuned a converged baseline for 25–30 epochs (10 frozen")
    A("backbone layers for M3/M4) against M1's 100 epochs — it measured fine-tuning damage, not")
    A("the interventions. Proof from the old artifacts themselves: the identity-mapped ANCHOR")
    A("(≈ M1 functionally, zero training) scored 0.7607–0.7608, above every trained variant.")
    A("")
    A("## D. New results with no old counterpart")
    A("")
    for r in attn:
        if r["model_id"] in ("M3se", "M3cbam"):
            A(f"- {r['attention']} at same insertion points: NEU mAP@0.5 {r['neu_mAP50']} "
              f"(Δ vs ECA+spatial {r.get('delta_neu_mAP50_vs_M3m_pp','?')} pp, p={r.get('delta_neu_p','?')}); "
              f"params {int(float(r['params_total'])):,} vs 9,430,429. (attention_alternatives.csv)")
    pp = read_csv(RV3 / "preprocessing_controls.csv")
    for r in pp:
        if r["model_id"] == "M2gray":
            A(f"- Grayscale-CLAHE control (no LAB, no bilateral): NEU mAP@0.5 {r['neu_mAP50']} "
              f"(Δ vs LAB+bilateral {r.get('delta_neu_mAP50_vs_M2m_pp','?')} pp, p={r.get('delta_neu_p','?')}). (preprocessing_controls.csv)")
    A("- Zero-shot transfer controls: multi-scale (640/1024/1280), defect-scale-matched tiling,")
    A("  per-GC10-class breakdown, restricted-overlap protocol, preprocessing-on/off — see")
    A("  `transfer_controls.csv`, `gc10_restricted_*.csv`. Transfer exists only on blob/texture")
    A("  classes (oil_spot, punching_hole, crescent_gap), ≈0.001 on semantically matching classes.")
    gc = read_csv(RV3 / "phase3" / "gradcam_quant.csv")
    if gc:
        fused = [r for r in gc if r["scale"] == "fused"]
        A("- Quantified Grad-CAM (whole test split, pointing game / energy-in-GT, CIs):")
        for r in fused:
            A(f"  - {r['model']}: PG-all {r['pointing_game_all']} [{r['pg_all_ci_low']},{r['pg_all_ci_high']}], "
              f"PG-cond {r['pointing_game_cond']}, energy {r['energy_in_gt']} [{r['energy_ci_low']},{r['energy_ci_high']}]")
        A("  (phase3/gradcam_quant.csv)")
    A("")
    A("## E. Claims removed from the report text")
    A("")
    A("- 'strongly confirmed', 'statistically significant' (without a test), 'the only deployable model'")
    A("- 'first joint illumination-attention study', 'first zero-shot cross-mill protocol' (prior art: refs [1-4,8,9])")
    A("- CIE L*a*b* chromaticity rationale (both datasets grayscale), 'ray-traced contrast limit'")
    A("- self-driving-car analogy; 'halved false alarms'")
    A("- Grad-CAM boundary-level claims from 3 hand-picked images (replaced by §5.6 quantification)")
    A("")
    A("## F. Verdict changes")
    A("")
    A("| hypothesis | old verdict | new verdict |")
    A("|---|---|---|")
    A("| H1 preprocessing helps in-domain | 'strongly confirmed' | **NOT SUPPORTED** (+0.31 pp, p=0.67; harms transfer −0.73 pp, p=0.014) |")
    A("| H2 attention helps in-domain | 'confirmed' (via M3 cherry-picks) | **SUPPORTED weakly via full model** (+2.02 pp mAP@0.5, p=0.038; 5095 inconclusive; attention-only p=0.18; not module-specific: SE ties/wins) |")
    A("| H3 real-time | 'confirmed' | **SUPPORTED** (≥58 FPS fp32 batch-1, controlled protocol; attention ≈ +13% inference latency) |")
    A("| H4 cross-dataset synergy | 'confirmed, +49.8%' | **NOT SUPPORTED** (all-image zero-shot: modifications neutral-to-harmful; M4 −1.03 pp, p<0.001) |")
    (RV3 / "CHANGELOG.md").write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {RV3 / 'CHANGELOG.md'} ({len(L)} lines)")


if __name__ == "__main__":
    main()
